### ISSUE TITLE
Clarification in the README

### ISSUE THREAD

**Issue by tomduckering** [alanfranz/docker-rpm-builder#10]
Hi - not sure the best way to raise this but you state in the README that RPMs are not well suited to CI because one needs to create an SRPM first. Perhaps you could clarify.

I ask because recently I was working for a client where we were building RPMs using [FPM](https://github.com/jordansissel/fpm) and we had no need to build intermediate SRPMs. Also I think there is no reason why you can't write spec files which don't require SRPMs. All this was very fast and not a hindrance to our deployment pipeline. To be clear in this case the code was being written in clojure, compiled to an uberjar and then this was packaged as an RPM (including init scripts, logging snippets, monitoring snippets etc).

I hope that helps clarify my confusion. Thanks again for building this and sharing it with the community.

**Comment by alanfranz** [comment]
You are right, I was thinking myself about clarifying that point.

You don't need an intermediate .src.rpm if you're using plain rpmbuild (which is what fpm does under the hood AFAIK), which limits you to building on the very same target distro as your host (and you need rpmbuild on your host). If you use mock, then you need to build a .src.rpm before building your binary rpm. 

I'll update the readme shortly.

**Comment by alanfranz** [comment]
Also, your pipeline probably requires little to nothing native code - you don't need a reproducible build environment, clojure just generates plain java bytecode which is architecture independent. I use fpm as well for such tasks, but you can't do everything with fpm; it doesn't handle build dependencies (which are required in order to make builds reproducible), hence it's not suitable for native packages.
