### ISSUE TITLE
Method for installing BuildRequires packages broken at times

### ISSUE THREAD

**Issue by sadris** [alanfranz/docker-rpm-builder#11]
I'm trying to build php55w on Centos 5 (https://github.com/webtatic-rpms/php55w). It is failing to fetch certain requirements. For example, it wants libxml2-devel >= 2.4.14-1:

```
+ for v in '${BUILDREQUIRES}'
+ yum info 'libxml2-devel>=2.4.14-1'
Error: No matching Packages to list
+++ arch
++ repoquery --arch=x86_64 --whatprovides 'libxml2-devel>=2.4.14-1'
+ PACKAGE=
```
So both `yum info libxml2-devel>=2.4.14-1` and the repoquery command fails. However, `yum info libxml2-devel` returns that 2.6.26 is available. Also, running repoquery with `libxml2-devel >= 2.4.14-1` (notice the spaces) returns a found result. It looks like the RPM::Toolbox::Spec perl module is returning strings without spaces in the comparison operators (called from your script /tmp/parse-spec-build-requires.pl) and then repoquery is unable to find results. This is probably an issue with rpmtoolbox, but that hasn't been updated since 2010. You may be able to do a sed command on the rpmtoolbox output to insert spaces to let the repoquery command succeed.

**Comment by alanfranz** [comment]
Hello,
this is an issue with alanfranz/drb-epel-5-x86-64 in
https://github.com/alanfranz/docker-rpm-builder-configurations rather
than with docker-rpm-builder.

As you can read on such page, yum-builddep was hacked for such config,
since the yum-builddep version in centos 5 doesn't support raw
specfiles (you need a .src.rpm and install it on the host system).

I'm taking a look at the issue, but I cannot make any guarantee about
that to be finally working. I'll gladly accept patches by the way!

**Comment by alanfranz** [comment]
Hello,
there's a new alanfranz/drb-epel-5-x86-64:latest image with an updated approach to yum-builddep; I think that it should fit your needs. I cannot build your php55w because it needs something like libicu42-devel which it cannot find, but it actually seems that it's trying to properly download dependencies.

Feel free to open another ticket (better on https://github.com/alanfranz/docker-rpm-builder-configurations) if it's still an issue.
