### ISSUE TITLE
Is there an option to build a src.rpm in case I need it?

### ISSUE THREAD

**Issue by iav** [alanfranz/docker-rpm-builder#21]
Is there an option to build a src.rpm in case I need it?

**Comment by aframachines** [comment]
Uhm.. so you would like to build a .src.rpm beside your binary RPM?

**Comment by iav** [comment]
Yes. For archive and distribution purposes (originally I build from source tree).

**Comment by aframachines** [comment]
I need to think a bit about it. For sure it's doable, but then I should be
confident that whatever is built straight from the source dir is identical
to what would be built from the .src.rpm - at least that's how I'd think it
should work, if it doesn't, then it's an issue.

I'm doing a couple of experiments to see if there's a proper way to do it.

**Comment by iav** [comment]
Thank you!

**Comment by alanfranz** [comment]
Hello,
I believed I had commented on this about one week ago. But I must have forgotten to press the enter key.

After experimenting, I have some questions.

I deem this unuseful if it isn't "chained" - i.e. in order to have this work properly, I would need to build a .src.rpm , and then build the binary rpm from that. I wouldn't accept anything different. But this would make the tool slower and you would need to change a bit from the current _dir_ command usage, doing something more similar to rpmbuild/mock - I haven't found a way to make a .src.rpm perform like a dir command, since it's a bit different.

Would you think something like that to be useful and/or acceptable?

**Comment by iav** [comment]
Probably, it is not worth the cost.

**Comment by alanfranz** [comment]
ok, so I'm closing this right now. If I happen to have any interesting idea on the topic I'll let you know.

**Comment by iav** [comment]
It's easy and fast to get src.rpm file from docker-rpm-builder in case I need it:
1. run `docker-rpm-builder` with `--verbose --preserve-container` options
   If build successfull, on screen, on end of a long scroll, should be lines like

```
Wrote: /root/rpmbuild/SRPMS/myprogram-1.0.0-1.el7.centos.src.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/myprogram-1.0.0-1.el7.centos.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/myprogram-debuginfo-1.0.0-1.el7.centos.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.4ghYFq
```
1. after successful build find container in `docker ps -a` output
   It should be something like

```
2b023493aa4e        centos7-64          "./rpmbuild-dir-in-do"   3 minutes ago       Exited (0) 2 minutes ago
```
1. just take src.rpm seen in 1: 

```
docker cp 2b023493aa4e:/root/rpmbuild/SRPMS/myprogram-1.0.0-1.el7.centos.src.rpm .
```

**Comment by alanfranz** [comment]
I suppose you tried rebuilding a binary rpm from that .src.rpm, right? :-)

**Comment by iav** [comment]
Eee... Not yet. Thank you for pointing to. Will try on a week.
Or - do you want to say it will be broken srpm?

**Comment by alanfranz** [comment]
It will contain the source .spec only. I don't remember why I used "-ba" instead of "-bb" in my rpmbuild script, it was probably for debugging purposes, then I left it as it is since it had very little overhead.

If you've got any proposal on how the tool should behave for building a .src.rpm beside a binary rpm please put it forward, by the way.

Also: if you REALLY need what you say need, feel free to skip docker-rpm-builder entirely. Just use docker with the images I provide, bind the SOURCES, SRPMS, RPMS directory with the proper files inside, and call "rpmbuild -ba" directly.

**Comment by iav** [comment]
Main reason I like your tool - fast and easy. No mess with setting variables, building trees, envs, and so on. And it's reason why I ping you with stupid questions. 
I use your tool to modify or rpm-ify packets, and consttantly go on cycle "build - look to results - modify".
And yes, I am keeping in backgroud "I will try to add to this tool an option to do all preparations to package building and open ready shell where I can run rpmbuild -ba or any intermediate rpmbuild stage then tin in sources as long as I need"
But I understand it's not what for you made this tool.

**Comment by alanfranz** [comment]
Hello @iav  , could you please take a look at #35 and tell me what you think?
